buildscript {
    repositories { maven { url='https://maven.minecraftforge.net/' }; mavenCentral() }
    dependencies { classpath 'net.minecraftforge.gradle:ForgeGradle:3.+' }
}
apply plugin:'net.minecraftforge.gradle'
apply plugin:'java'
version='0.2a-legacy-preview.1'
group='net.foundations.pl4'
archivesBaseName='FoundationsPL4-1.12.2'
sourceCompatibility=targetCompatibility='1.8'
sourceSets {
    main { java.srcDirs=['src/legacy/java']; resources.srcDirs=['src/legacy/resources'] }
    legacyTest { compileClasspath+=sourceSets.main.output+sourceSets.main.compileClasspath; runtimeClasspath+=sourceSets.main.output+sourceSets.main.runtimeClasspath }
    legacyRules { java.srcDirs=['tools']; java.include 'CoreChecks.java'; compileClasspath+=sourceSets.main.output; runtimeClasspath+=sourceSets.main.output }
}
minecraft {
    mappings channel:'snapshot',version:'20171003-1.12'
    runs {
        client { workingDirectory project.file('run'); mods { foundations_pl4 { source sourceSets.main } } }
        server {
            workingDirectory project.file(project.hasProperty('legacyScenarios')?'run-legacy':'run')
            args '--nogui'
            mods { foundations_pl4 { source sourceSets.main } }
            if(project.hasProperty('legacyScenarios')) {
                property 'foundations_pl4.legacyScenarios','true'
                mods { foundations_pl4_legacytests { source sourceSets.legacyTest } }
            }
        }
    }
}
repositories { mavenCentral() }
dependencies { minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2864' }
tasks.withType(JavaCompile).all { options.encoding='UTF-8' }
processResources {
    inputs.property 'version',project.version
    filesMatching('mcmod.info') { expand 'version':project.version }
    from('src/main/resources') {
        include 'assets/foundations_pl4/textures/block/data_cable.png'
        include 'assets/foundations_pl4/textures/block/model/transfer_node_remove.png'
        include 'assets/foundations_pl4/textures/block/model/transfer_node_add.png'
    }
}
jar { from('LICENSE'); from('LICENSE-SonarCore'); from('NOTICE'); manifest { attributes('Implementation-Version':project.version) }; finalizedBy 'reobfJar' }
task sourcesJar(type:Jar) { from sourceSets.main.allSource; classifier='sources' }
task legacyRules(type:JavaExec) { dependsOn legacyRulesClasses; classpath=sourceSets.legacyRules.runtimeClasspath; main='CoreChecks' }
check.dependsOn legacyRules
build.dependsOn sourcesJar
if(project.hasProperty('legacyScenarios')) tasks.matching { it.name=='runServer' }.all { dependsOn legacyTestClasses }
tasks.withType(AbstractArchiveTask).all { preserveFileTimestamps=false; reproducibleFileOrder=true }
