modLoader="javafml"
loaderVersion="[34,35)"
license="MIT"
[[mods]]
modId="foundations_pl4"
version="${version}"
displayName="Foundations PL4"
authors="Foundations; original Practical Logistics and Sonar Core by Ollie Lansdell (SonarSonic)"
description="Standalone Practical Logistics. Forge port development build; further API testing is required."
[[dependencies.foundations_pl4]]
modId="forge"
mandatory=true
versionRange="[34.1.42,35)"
ordering="NONE"
side="BOTH"
[[dependencies.foundations_pl4]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3]"
ordering="NONE"
side="BOTH"
