modLoader="javafml"
loaderVersion="[32,33)"
license="MIT"
[[mods]]
modId="foundations_pl4_porttests"
version="1"
displayName="PL4 isolated native scenarios (development only)"
[[dependencies.foundations_pl4_porttests]]
modId="foundations_pl4"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="SERVER"
[[dependencies.foundations_pl4_porttests]]
modId="minecraft"
mandatory=true
versionRange="[1.16.1]"
ordering="NONE"
side="SERVER"
