package net.foundations.pl4.legacy.tests;
import java.io.File;
import java.io.FileWriter;
import java.util.UUID;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.mojang.authlib.GameProfile;
import net.foundations.pl4.legacy.*;
import net.minecraftforge.fluids.*;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.entity.item.EntityItem;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.server.MinecraftServer;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.tileentity.TileEntityFurnace;
import net.minecraft.util.math.AxisAlignedBB;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.WorldServer;
import net.minecraftforge.common.util.FakePlayerFactory;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.event.FMLServerStartedEvent;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.registry.ForgeRegistries;
/** Disposable server only. This separate source set is never packaged in the runtime JAR. */
@Mod(modid="foundations_pl4_legacytests",name="PL4 legacy native scenarios",version="1",dependencies="required-after:foundations_pl4",acceptableRemoteVersions="*")
public final class NativeScenarios {
    private static final UUID OWNER=UUID.fromString("fae1b877-c6b4-4538-a26a-630190b54205");
    private WorldServer world;private int total,passed;private JsonArray results=new JsonArray();
    private final BlockPos export=new BlockPos(0,200,0),cable=new BlockPos(1,200,0),sink=new BlockPos(2,200,0);
    @Mod.EventHandler public void started(FMLServerStartedEvent event)throws Exception{
        if(!Boolean.getBoolean("foundations_pl4.legacyScenarios"))throw new IllegalStateException("Test mod requires disposable scenario server");
        MinecraftServer server=FMLCommonHandler.instance().getMinecraftServerInstance();world=server.getWorld(0);
        if(!server.getFolderName().equals("pl4-legacy-test-world"))throw new IllegalStateException("Refusing non-test world");
        try{
            test("registered native blocks and recipes",()->{check(ForgeRegistries.BLOCKS.getValue(LegacyPL4.CABLE.getRegistryName())==LegacyPL4.CABLE,"cable registration");int count=0;for(net.minecraft.item.crafting.IRecipe r:ForgeRegistries.RECIPES)if(r.getRegistryName()!=null&&r.getRegistryName().getResourceDomain().equals(LegacyPL4.ID))count++;check(count==12,"actual recipe count");});
            test("owner separated physical topology",()->check(node(export).network().nodes.size()==3,"network size"));
            test("eight items transferred and conserved",()->{source().setInventorySlotContents(0,new ItemStack(Items.IRON_INGOT,32));check(node(export).transferOnce()==8,"move rate");check(source().getStackInSlot(0).getCount()==24&&destination().getStackInSlot(0).getCount()==8,"conservation");});
            test("full destination leaves source unchanged",()->{source().setInventorySlotContents(0,new ItemStack(Items.IRON_INGOT,32));for(int i=0;i<27;i++)destination().setInventorySlotContents(i,new ItemStack(Items.STICK,64));check(node(export).transferOnce()==0&&source().getStackInSlot(0).getCount()==32,"full target");});
            test("disabled transfer configuration",()->{source().setInventorySlotContents(0,new ItemStack(Items.IRON_INGOT,32));LegacyPL4.enabled=false;check(node(export).transferOnce()==0&&source().getStackInSlot(0).getCount()==32,"disabled transfer");});
            test("foreign owner cannot receive",()->{source().setInventorySlotContents(0,new ItemStack(Items.IRON_INGOT,32));node(sink).owner=UUID.randomUUID().toString();check(node(export).transferOnce()==0,"foreign import");});
            test("foreign cable partitions network",()->{node(cable).owner=UUID.randomUUID().toString();check(node(export).network().nodes.size()==1,"partition");});
            test("removed cable disconnects inventory",()->{source().setInventorySlotContents(0,new ItemStack(Items.IRON_INGOT,32));world.setBlockToAir(cable);check(node(export).transferOnce()==0,"disconnect");});
            test("oversized graph fails closed",()->{LegacyPL4.nodeLimit=2;source().setInventorySlotContents(0,new ItemStack(Items.IRON_INGOT,32));check(node(export).network().overflow&&node(export).transferOnce()==0,"overflow");});
            test("NBT variants do not coalesce",()->{ItemStack a=new ItemStack(Items.IRON_INGOT,16);a.setStackDisplayName("A");ItemStack b=new ItemStack(Items.IRON_INGOT,10);b.setStackDisplayName("B");source().setInventorySlotContents(0,a);destination().setInventorySlotContents(0,b);check(node(export).transferOnce()==8,"variant moved");check(destination().getStackInSlot(0).getCount()==10&&destination().getStackInSlot(1).getDisplayName().equals("A"),"variant isolation");});
            test("escrow survives native NBT serialization",()->{LegacyTile original=node(export);original.pending=new ItemStack(Items.DIAMOND,5);NBTTagCompound tag=original.writeToNBT(new NBTTagCompound());LegacyTile restored=new LegacyTile();restored.readFromNBT(tag);check(restored.pending.getCount()==5&&restored.pending.getItem()==Items.DIAMOND&&restored.owner.equals(original.owner)&&restored.side==4,"persisted escrow and identity");});
            test("escrow drains even when source disappears",()->{node(export).pending=new ItemStack(Items.DIAMOND,5);world.setBlockToAir(export.west());check(node(export).transferOnce()==5&&node(export).pending.isEmpty()&&destination().getStackInSlot(0).getCount()==5,"source unavailable escrow");});
            test("malformed direction clamped on load",()->{NBTTagCompound tag=node(export).writeToNBT(new NBTTagCompound());tag.setInteger("Side",500);LegacyTile restored=new LegacyTile();restored.readFromNBT(tag);check(restored.side>=0&&restored.side<6,"direction bound");});
            test("unloaded graph does not load chunks",()->{int before=world.getChunkProvider().getLoadedChunkCount();node(export).network();check(before==world.getChunkProvider().getLoadedChunkCount(),"no new chunks");});
            test("owner edit permitted and stranger denied",()->{check(node(export).canEdit(FakePlayerFactory.get(world,new GameProfile(OWNER,"Owner"))),"owner access");check(!node(export).canEdit(FakePlayerFactory.get(world,new GameProfile(UUID.fromString("7870f566-beb8-45ae-a0f6-d96b5678a529"),"Other"))),"stranger denied");});
            test("source redstone pauses transport",()->{source().setInventorySlotContents(0,new ItemStack(Items.IRON_INGOT,32));world.setBlockState(export.up(),Blocks.REDSTONE_BLOCK.getDefaultState(),3);check(world.isBlockPowered(export)&&node(export).transferOnce()==0,"redstone pause");});
            test("sink redstone pauses import",()->{source().setInventorySlotContents(0,new ItemStack(Items.IRON_INGOT,32));world.setBlockState(sink.up(),Blocks.REDSTONE_BLOCK.getDefaultState(),3);check(node(export).transferOnce()==0,"sink redstone");});
            test("native sided furnace extraction",()->{world.setBlockState(export.west(),Blocks.FURNACE.getDefaultState(),3);TileEntityFurnace f=(TileEntityFurnace)world.getTileEntity(export.west());f.setInventorySlotContents(0,new ItemStack(Blocks.IRON_ORE,5));check(node(export).inventory().extractItem(0,1,true).isEmpty(),"sided extraction guard");});
            test("source scan respects slot limit",()->{LegacyPL4.slotLimit=1;source().setInventorySlotContents(5,new ItemStack(Items.IRON_INGOT,32));check(node(export).transferOnce()==0,"slot cap");});
            test("empty native inventories are inert",()->check(node(export).transferOnce()==0&&node(export).pending.isEmpty(),"empty source"));
            // reset() discards fixture drops with setDead(). Until the next tick those removed entities
            // can remain in the spatial query; only live drops belong to this exact-once assertion.
            test("pending buffer released when host removed",()->{node(export).pending=new ItemStack(Items.DIAMOND,5);world.setBlockToAir(export);int count=0;for(EntityItem item:world.getEntitiesWithinAABB(EntityItem.class,new AxisAlignedBB(-2,199,-2,5,203,2)))if(!item.isDead&&item.getItem().getItem()==Items.DIAMOND)count+=item.getItem().getCount();check(count==5,"escrow drop exactly once (live count="+count+")");});
                    test("tank capacity and simulation",new Runnable(){public void run(){setupFluids();check(fluidNode(-1).fluid.fill(water(20000),true)==16000&&fluidNode(-1).fluid.storedAmount()==0,"fill simulation");check(fluidNode(-1).fluid.fill(water(20000),false)==16000,"tank capacity");check(fluidNode(-1).fluid.drain(1000,true).amount==1000&&fluidNode(-1).fluid.storedAmount()==16000,"drain simulation");}});
            test("tank does not bridge physical data network",new Runnable(){public void run(){setupFluids();check(fluidNode(0).network().nodes.size()==3,"only cable and fluid endpoints in graph");}});
            test("native fluid transfer rate and conservation",new Runnable(){public void run(){setupFluids();fluidNode(-1).fluid.fill(water(1000),false);check(fluidNode(0).transferOnce()==250,"fluid rate");check(fluidNode(-1).fluid.storedAmount()==750&&fluidNode(3).fluid.storedAmount()==250,"fluid conservation");}});
            test("full fluid destination leaves source untouched",new Runnable(){public void run(){setupFluids();fluidNode(-1).fluid.fill(water(1000),false);fluidNode(3).fluid.fill(water(16000),false);check(fluidNode(0).transferOnce()==0&&fluidNode(-1).fluid.storedAmount()==1000,"full tank");}});
            test("different fluid does not mix",new Runnable(){public void run(){setupFluids();fluidNode(-1).fluid.fill(water(1000),false);fluidNode(3).fluid.fill(new FluidStack(FluidRegistry.LAVA,1000),false);check(fluidNode(0).transferOnce()==0&&fluidNode(-1).fluid.storedAmount()==1000,"no mixing");}});
            test("fluid NBT variants stay separate",new Runnable(){public void run(){setupFluids();FluidStack tagged=water(1000);tagged.tag=new NBTTagCompound();tagged.tag.setString("Grade","A");fluidNode(-1).fluid.fill(tagged,false);fluidNode(3).fluid.fill(water(1000),false);check(fluidNode(0).transferOnce()==0,"NBT variant cannot coalesce");}});
            test("fluid enable flag is respected",new Runnable(){public void run(){setupFluids();fluidNode(-1).fluid.fill(water(1000),false);LegacyPL4.fluidsEnabled=false;check(fluidNode(0).transferOnce()==0&&fluidNode(-1).fluid.storedAmount()==1000,"fluid switch");}});
            test("global transfer flag stops fluids",new Runnable(){public void run(){setupFluids();fluidNode(-1).fluid.fill(water(1000),false);LegacyPL4.enabled=false;check(fluidNode(0).transferOnce()==0,"global switch");}});
            test("foreign tank cannot receive PL4 fluids",new Runnable(){public void run(){setupFluids();fluidNode(-1).fluid.fill(water(1000),false);fluidNode(3).owner="other";check(fluidNode(0).transferOnce()==0&&fluidNode(-1).fluid.storedAmount()==1000,"foreign tank");}});
            test("foreign fluid source tank is rejected",new Runnable(){public void run(){setupFluids();fluidNode(-1).fluid.fill(water(1000),false);fluidNode(-1).owner="other";check(fluidNode(0).transferOnce()==0,"source tank ownership");}});
            test("removed cable disconnects fluids",new Runnable(){public void run(){setupFluids();fluidNode(-1).fluid.fill(water(1000),false);fluidAir(1,200);check(fluidNode(0).transferOnce()==0,"fluid disconnect");}});
            test("oversized fluid network fails closed",new Runnable(){public void run(){setupFluids();fluidNode(-1).fluid.fill(water(1000),false);LegacyPL4.nodeLimit=2;check(fluidNode(0).transferOnce()==0&&fluidNode(0).network().overflow,"fluid topology cap");}});
            test("fluid exporter redstone pause",new Runnable(){public void run(){setupFluids();fluidNode(-1).fluid.fill(water(1000),false);fluidPower(0);check(fluidNode(0).transferOnce()==0,"fluid export pause");}});
            test("fluid importer redstone pause",new Runnable(){public void run(){setupFluids();fluidNode(-1).fluid.fill(water(1000),false);fluidPower(2);check(fluidNode(0).transferOnce()==0,"fluid import pause");}});
            test("fluid escrow survives source removal",new Runnable(){public void run(){setupFluids();fluidNode(0).fluid.set(water(123));fluidAir(-1,200);check(fluidNode(0).transferOnce()==123&&fluidNode(0).fluid.get()==null&&fluidNode(3).fluid.storedAmount()==123,"drain orphan escrow");}});
            test("fluid state persists through native NBT",new Runnable(){public void run(){setupFluids();fluidNode(0).fluid.set(water(99));fluidNode(0).fluid.block("native persistence test");NBTTagCompound tag=saveFluid(fluidNode(0));LegacyTile copy=new LegacyTile();copy.readFromNBT(tag);check(copy.fluid.get().amount==99&&copy.fluid.blocked(),"fluid fault and amount persisted");}});
            test("built-in tank content persists through native NBT",new Runnable(){public void run(){setupFluids();fluidNode(3).fluid.fill(water(3456),false);LegacyTile copy=new LegacyTile();copy.readFromNBT(saveFluid(fluidNode(3)));check(copy.fluid.storedAmount()==3456,"tank content persisted");}});
            test("unknown fluid NBT survives round trip",new Runnable(){public void run(){setupFluids();NBTTagCompound raw=new NBTTagCompound();raw.setString("FluidName","pl4_missing_test_fluid");raw.setInteger("Amount",1234);NBTTagCompound tag=saveFluid(fluidNode(3));tag.setTag("FluidTank",raw);LegacyTile copy=new LegacyTile();copy.readFromNBT(tag);NBTTagCompound saved=saveFluid(copy);check(saved.getCompoundTag("FluidTank").getString("FluidName").equals("pl4_missing_test_fluid")&&saved.getCompoundTag("FluidTank").getInteger("Amount")==1234,"unresolved fluid retained");}});
            test("fluid removal creates exactly one recovery cell",new Runnable(){public void run(){setupFluids();fluidNode(3).fluid.fill(water(1234),false);fluidAir(3,200);check(fluidCells()==1,"one sealed cell drop");}});
            test("healthy recovery cell restores fluid",new Runnable(){public void run(){setupFluids();fluidNode(-1).fluid.fill(water(1234),false);ItemStack cell=new ItemStack(LegacyPL4.FLUID_CELL);cell.setTagCompound(fluidNode(-1).fluid.recovery().get(0));check(LegacyFluidPlatform.interact(fluidNode(3),fluidPlayer(),cell)&&fluidNode(3).fluid.storedAmount()==1234&&!cell.getTagCompound().hasKey("Contents"),"cell restoration");}});
            test("partial recovery leaves remainder in cell",new Runnable(){public void run(){setupFluids();fluidNode(-1).fluid.fill(water(250),false);fluidNode(3).fluid.fill(water(15990),false);NBTTagCompound cell=fluidNode(-1).fluid.recovery().get(0);check(fluidNode(3).fluid.restore(cell)==10&&cell.getCompoundTag("Contents").getInteger("Amount")==240&&fluidNode(3).fluid.storedAmount()==16000,"partial cell");}});
            test("quarantined cell cannot replay uncertain fluid",new Runnable(){public void run(){setupFluids();fluidNode(0).fluid.set(water(250));fluidNode(0).fluid.block("uncertain provider operation");NBTTagCompound cell=fluidNode(0).fluid.recovery().get(0);check(fluidNode(3).fluid.restore(cell)==0&&cell.getCompoundTag("Contents").getInteger("Amount")==250,"quarantine cannot restore");}});
            test("owner check protects tank interaction",new Runnable(){public void run(){setupFluids();fluidNode(3).owner="other";ItemStack bucket=waterBucket();check(!LegacyFluidPlatform.interact(fluidNode(3),fluidPlayer(),bucket)&&fluidNode(3).fluid.storedAmount()==0,"stranger cannot use tank");}});
            test("vanilla bucket fills built-in tank",new Runnable(){public void run(){setupFluids();ItemStack bucket=waterBucket();check(LegacyFluidPlatform.interact(fluidNode(3),fluidPlayer(),bucket)&&fluidNode(3).fluid.storedAmount()==1000,"bucket fill");}});
            test("tagged fluid cannot become plain vanilla bucket",new Runnable(){public void run(){setupFluids();FluidStack tagged=water(1000);tagged.tag=new NBTTagCompound();tagged.tag.setString("Grade","A");fluidNode(3).fluid.fill(tagged,false);LegacyFluidPlatform.interact(fluidNode(3),fluidPlayer(),emptyBucket());check(fluidNode(3).fluid.storedAmount()==1000,"bucket preserves tags");}});
            test("fluid scans do not add loaded chunks",new Runnable(){public void run(){setupFluids();fluidNode(-1).fluid.fill(water(1000),false);int before=world.getChunkProvider().getLoadedChunkCount();fluidNode(0).transferOnce();check(world.getChunkProvider().getLoadedChunkCount()==before,"fluid scan loaded-only");}});
            test("native sided external fluid handler",new Runnable(){public void run(){setupFluids();ExternalTank dest=externalTank();fluidNode(-1).fluid.fill(water(1000),false);check(fluidNode(0).transferOnce()==250&&dest.tank.getFluidAmount()==250,"external native fluid API");}});
            test("external handler denied face does not fall back",new Runnable(){public void run(){setupFluids();ExternalTank dest=externalTank();dest.deny=true;fluidNode(-1).fluid.fill(water(1000),false);check(fluidNode(0).transferOnce()==0&&fluidNode(-1).fluid.storedAmount()==1000,"no unsided fallback");}});
            test("actual refusal preserves and later drains escrow",new Runnable(){public void run(){setupFluids();ExternalTank dest=externalTank();dest.refuse=true;fluidNode(-1).fluid.fill(water(1000),false);check(fluidNode(0).transferOnce()==0&&fluidNode(0).fluid.get().amount==250&&!fluidNode(0).fluid.blocked(),"refusal escrow");dest.refuse=false;check(fluidNode(0).transferOnce()==250&&fluidNode(-1).fluid.storedAmount()==750,"no repeated extraction");}});
            test("native provider exception quarantines without retry",new Runnable(){public void run(){setupFluids();ExternalTank dest=externalTank();dest.fail=true;fluidNode(-1).fluid.fill(water(1000),false);try{fluidNode(0).transferOnce();throw new AssertionError("provider exception expected");}catch(IllegalStateException expected){}check(fluidNode(0).fluid.blocked()&&fluidNode(0).fluid.get().amount==250,"quarantined escrow");int calls=dest.executed;check(fluidNode(0).transferOnce()==0&&dest.executed==calls,"no retry after exception");}});
            test("energy buffers and nodes registered with recipes",new Runnable(){public void run(){setupEnergy();check(fluidNode(0).role()==6&&fluidNode(2).role()==7&&fluidNode(3).role()==8,"energy roles");check(LegacyPL4.ENERGY_CELL!=null,"recovery item registration");}});
            test("energy storage simulation is pure",new Runnable(){public void run(){setupEnergy();LegacyEnergy.State s=fluidNode(-1).energy;check(s.receive(1000,true)==1000&&s.stored()==0,"simulated charge");s.receive(1000,false);check(s.extract(500,true)==500&&s.stored()==1000,"simulated discharge");}});
            test("energy storage handles bounded and negative amounts",new Runnable(){public void run(){setupEnergy();LegacyEnergy.State s=fluidNode(-1).energy;check(s.receive(-1,false)==0&&s.extract(-1,false)==0,"negative requests rejected");check(s.receive(Integer.MAX_VALUE,false)==100000&&s.stored()==100000,"capacity bound");check(s.extract(Integer.MAX_VALUE,false)==100000&&s.stored()==0,"available bound");}});
            test("energy transfer conserves source and sink",new Runnable(){public void run(){setupEnergy();fluidNode(-1).energy.receive(1000,false);check(fluidNode(0).transferOnce()==400&&fluidNode(-1).energy.stored()==600&&fluidNode(3).energy.stored()==400,"energy conservation");}});
            test("energy configured transfer rate",new Runnable(){public void run(){setupEnergy();LegacyPL4.energyRate=123;fluidNode(-1).energy.receive(1000,false);check(fluidNode(0).transferOnce()==123,"custom rate");}});
            test("energy full sink never extracts",new Runnable(){public void run(){setupEnergy();fluidNode(-1).energy.receive(1000,false);fluidNode(3).energy.receive(100000,false);check(fluidNode(0).transferOnce()==0&&fluidNode(-1).energy.stored()==1000,"full sink conservation");}});
            test("energy partial receiving space",new Runnable(){public void run(){setupEnergy();fluidNode(-1).energy.receive(1000,false);fluidNode(3).energy.receive(99975,false);check(fluidNode(0).transferOnce()==25&&fluidNode(-1).energy.stored()==975,"partial capacity");}});
            test("energy disabled independently",new Runnable(){public void run(){setupEnergy();fluidNode(-1).energy.receive(1000,false);LegacyPL4.energyEnabled=false;check(fluidNode(0).transferOnce()==0&&fluidNode(-1).energy.stored()==1000,"energy off");}});
            test("energy global disable",new Runnable(){public void run(){setupEnergy();fluidNode(-1).energy.receive(1000,false);LegacyPL4.enabled=false;check(fluidNode(0).transferOnce()==0,"global off");}});
            test("energy export redstone pause",new Runnable(){public void run(){setupEnergy();fluidNode(-1).energy.receive(1000,false);fluidPower(0);check(fluidNode(0).transferOnce()==0,"export paused");}});
            test("energy import redstone pause",new Runnable(){public void run(){setupEnergy();fluidNode(-1).energy.receive(1000,false);fluidPower(2);check(fluidNode(0).transferOnce()==0,"import paused");}});
            test("energy foreign source owner",new Runnable(){public void run(){setupEnergy();fluidNode(-1).energy.receive(1000,false);fluidNode(-1).owner="other";check(fluidNode(0).transferOnce()==0,"source owner enforced");}});
            test("energy foreign target owner",new Runnable(){public void run(){setupEnergy();fluidNode(-1).energy.receive(1000,false);fluidNode(3).owner="other";check(fluidNode(0).transferOnce()==0,"target owner enforced");}});
            test("energy foreign import owner",new Runnable(){public void run(){setupEnergy();fluidNode(-1).energy.receive(1000,false);fluidNode(2).owner="other";check(fluidNode(0).transferOnce()==0,"network owner enforced");}});
            test("energy buffers do not bridge networks",new Runnable(){public void run(){setupEnergy();fluidBlock(1,LegacyPL4.ENERGY_BUFFER);fluidNode(1).owner=fluidOwner();fluidNode(-1).energy.receive(1000,false);check(fluidNode(0).network().nodes.size()==1&&fluidNode(0).transferOnce()==0,"storage is endpoint");}});
            test("energy topology limit fails closed",new Runnable(){public void run(){setupEnergy();fluidNode(-1).energy.receive(1000,false);LegacyPL4.nodeLimit=2;check(fluidNode(0).transferOnce()==0&&fluidNode(-1).energy.stored()==1000,"oversized network");}});
            test("energy escrow drains without source",new Runnable(){public void run(){setupEnergy();fluidNode(0).energy.set(123);fluidAir(-1,200);check(fluidNode(0).transferOnce()==123&&fluidNode(3).energy.stored()==123&&fluidNode(0).energy.get()==0,"source-free flush");}});
            test("energy save roundtrip preserves stored and pending",new Runnable(){public void run(){setupEnergy();fluidNode(-1).energy.receive(5678,false);fluidNode(-1).energy.set(19);NBTTagCompound tag=saveFluid(fluidNode(-1));LegacyTile copy=new LegacyTile();copy.readFromNBT(tag);check(copy.energy.stored()==5678&&copy.energy.get()==19&&!copy.energy.blocked(),"save fields");}});
            test("old item and fluid saves load with zero energy",new Runnable(){public void run(){NBTTagCompound tag=saveFluid(fluidNode(0));tag.removeTag("PL4Energy");LegacyTile copy=new LegacyTile();copy.readFromNBT(tag);check(copy.energy.stored()==0&&copy.energy.get()==0&&!copy.energy.blocked(),"previous schema compatible");}});
            test("energy unknown units retained without conversion",new Runnable(){public void run(){setupEnergy();NBTTagCompound tag=saveFluid(fluidNode(-1));tag.getCompoundTag("PL4Energy").setString("Unit","EU");tag.getCompoundTag("PL4Energy").setInteger("Stored",1234);LegacyTile copy=new LegacyTile();copy.readFromNBT(tag);check(copy.energy.blocked(),"unknown unit blocked");check(copy.energy.recovery().getCompoundTag("PL4Energy").getString("Unit").equals("EU"),"opaque unit retained");check(fluidNode(3).energy.restore(copy.energy.recovery())==0,"no inferred conversion");}});
            test("energy negative saved amount quarantined",new Runnable(){public void run(){setupEnergy();NBTTagCompound tag=saveFluid(fluidNode(-1));tag.getCompoundTag("PL4Energy").setInteger("Stored",-5);LegacyTile copy=new LegacyTile();copy.readFromNBT(tag);check(copy.energy.blocked()&&copy.energy.recovery().getCompoundTag("PL4Energy").getInteger("Stored")==-5,"invalid amount retained");}});
            test("energy oversized saved escrow quarantined",new Runnable(){public void run(){setupEnergy();NBTTagCompound tag=saveFluid(fluidNode(-1));tag.getCompoundTag("PL4Energy").setInteger("Escrow",Integer.MAX_VALUE);LegacyTile copy=new LegacyTile();copy.readFromNBT(tag);check(copy.energy.blocked(),"oversize blocked");}});
            test("energy wrong numeric type retained",new Runnable(){public void run(){setupEnergy();NBTTagCompound tag=saveFluid(fluidNode(-1));tag.getCompoundTag("PL4Energy").setString("Stored","1000");LegacyTile copy=new LegacyTile();copy.readFromNBT(tag);check(copy.energy.blocked(),"numeric coercion rejected");}});
            test("energy recovery restores only original amount",new Runnable(){public void run(){setupEnergy();fluidNode(-1).energy.receive(1234,false);NBTTagCompound cell=fluidNode(-1).energy.recovery();fluidNode(-1).energy.clearRecovered();check(fluidNode(3).energy.restore(cell)==1234&&!cell.hasKey("PL4Energy")&&fluidNode(3).energy.restore(cell)==0,"single restore");}});
            test("energy recovery supports partial restore",new Runnable(){public void run(){setupEnergy();fluidNode(-1).energy.receive(1234,false);NBTTagCompound cell=fluidNode(-1).energy.recovery();fluidNode(3).energy.receive(99900,false);check(fluidNode(3).energy.restore(cell)==100&&cell.getCompoundTag("PL4Energy").getInteger("Stored")==1134,"recovery remainder");}});
            test("energy fault persists and blocks cell restore",new Runnable(){public void run(){setupEnergy();fluidNode(0).energy.set(100);fluidNode(0).energy.block("uncertain");LegacyTile copy=new LegacyTile();copy.readFromNBT(saveFluid(fluidNode(0)));check(copy.energy.blocked()&&copy.energy.get()==100&&fluidNode(3).energy.restore(copy.energy.recovery())==0,"no automatic uncertain restore");}});
            test("energy buffer removal drops one recovery cell",new Runnable(){public void run(){setupEnergy();fluidNode(-1).energy.receive(1234,false);LegacyTile old=fluidNode(-1);fluidAir(-1,200);LegacyEnergyPlatform.drop(old);check(energyCells(1234)==1,"exactly one recovery drop");}});
            test("energy manual generation is bounded per tick",new Runnable(){public void run(){setupEnergy();check(fluidNode(-1).energy.crank()==40&&fluidNode(-1).energy.crank()==0&&fluidNode(-1).energy.stored()==40,"manual cooldown");}});
            test("energy manual cooldown persists on reload",new Runnable(){public void run(){setupEnergy();LegacyTile tile=fluidNode(-1);tile.energy.crank();tile.readFromNBT(saveFluid(tile));check(tile.energy.crank()==0&&tile.energy.stored()==40,"saved cooldown");}});
            test("energy manual generation can be disabled",new Runnable(){public void run(){setupEnergy();LegacyPL4.manualEnergy=0;check(fluidNode(-1).energy.crank()==0,"manual off");}});
            test("energy diagnostics show unit and capacity",new Runnable(){public void run(){setupEnergy();check(fluidNode(-1).describe().contains(LegacyEnergyPlatform.UNIT)&&fluidNode(-1).describe().contains("100000"),"inspection fallback");}});
            test("energy native extension sided transfer",new Runnable(){public void run(){setupEnergy();ExternalEnergy dest=externalEnergy();fluidNode(-1).energy.receive(1000,false);check(fluidNode(0).transferOnce()==400&&dest.energy==400,"native energy endpoint");}});
            test("energy denied side never falls back",new Runnable(){public void run(){setupEnergy();ExternalEnergy dest=externalEnergy();dest.deny=true;fluidNode(-1).energy.receive(1000,false);check(fluidNode(0).transferOnce()==0&&fluidNode(-1).energy.stored()==1000,"no unsided retry");}});
            test("energy execute refusal retains escrow",new Runnable(){public void run(){setupEnergy();ExternalEnergy dest=externalEnergy();dest.refuse=true;fluidNode(-1).energy.receive(1000,false);check(fluidNode(0).transferOnce()==0&&fluidNode(0).energy.get()==400&&!fluidNode(0).energy.blocked(),"healthy retained escrow");dest.refuse=false;check(fluidNode(0).transferOnce()==400&&fluidNode(-1).energy.stored()==600,"no double extraction");}});
            test("energy provider failure after mutation quarantines",new Runnable(){public void run(){setupEnergy();ExternalEnergy dest=externalEnergy();dest.fail=true;fluidNode(-1).energy.receive(1000,false);try{fluidNode(0).transferOnce();throw new AssertionError("expected failure");}catch(IllegalStateException expected){}check(dest.energy==400&&fluidNode(0).energy.blocked(),"uncertain insertion");int calls=dest.executed;check(fluidNode(0).transferOnce()==0&&dest.executed==calls,"no replay");}});
            test("energy invalid simulation leaves source unchanged",new Runnable(){public void run(){setupEnergy();ExternalEnergy dest=externalEnergy();dest.bad=true;fluidNode(-1).energy.receive(1000,false);try{fluidNode(0).transferOnce();throw new AssertionError("expected invalid result");}catch(IllegalStateException expected){}check(fluidNode(-1).energy.stored()==1000&&fluidNode(0).energy.get()==0,"bad simulation safe");}});
            test("energy scans do not load new chunks",new Runnable(){public void run(){setupEnergy();fluidNode(-1).energy.receive(1000,false);int count=world.getChunkProvider().getLoadedChunkCount();fluidNode(0).transferOnce();check(world.getChunkProvider().getLoadedChunkCount()==count,"loaded-only energy scan");}});
            test("native fixture cleanup before world save",new Runnable(){public void run(){check(destination()!=null,"registered vanilla destination after reset");System.out.println("PL4 LEGACY FIXTURE CLEANUP: PASS");}});
        }finally{
            JsonObject report=new JsonObject();report.addProperty("minecraft","1.12.2");report.addProperty("total",total);report.addProperty("passed",passed);report.addProperty("failed",total-passed);report.add("results",results);
            try(FileWriter file=new FileWriter(new File("legacy-scenarios.json"))){new Gson().toJson(report,file);}
            System.out.println("PL4 LEGACY SCENARIOS: "+passed+"/"+total);server.initiateShutdown();
        }
    }
    private void test(String name,Runnable body){total++;JsonObject result=new JsonObject();result.addProperty("name",name);try{reset();body.run();passed++;result.addProperty("passed",true);}catch(Throwable error){result.addProperty("passed",false);result.addProperty("error",error.toString());error.printStackTrace();}results.add(result);}
    private void reset(){LegacyPL4.energyEnabled=true;LegacyPL4.energyRate=400;LegacyPL4.manualEnergy=40;LegacyPL4.fluidsEnabled=true;LegacyPL4.fluidRate=250;LegacyPL4.enabled=true;LegacyPL4.nodeLimit=256;LegacyPL4.slotLimit=256;LegacyPL4.itemRate=8;for(int x=-2;x<=4;x++)for(int y=199;y<=202;y++)for(int z=-1;z<=1;z++){world.getChunkFromBlockCoords(new BlockPos(x,y,z));world.setBlockToAir(new BlockPos(x,y,z));}for(EntityItem item:world.getEntitiesWithinAABB(EntityItem.class,new AxisAlignedBB(-3,198,-3,6,204,3)))item.setDead();world.setBlockState(export,LegacyPL4.EXPORT.getDefaultState(),3);world.setBlockState(cable,LegacyPL4.CABLE.getDefaultState(),3);world.setBlockState(sink,LegacyPL4.IMPORT.getDefaultState(),3);for(BlockPos p:new BlockPos[]{export,cable,sink})node(p).owner=OWNER.toString();node(export).side=4;node(sink).side=5;world.setBlockState(export.west(),Blocks.CHEST.getDefaultState(),3);world.setBlockState(sink.east(),Blocks.CHEST.getDefaultState(),3);}
    private LegacyTile node(BlockPos p){return (LegacyTile)world.getTileEntity(p);}
    private TileEntityChest source(){return (TileEntityChest)world.getTileEntity(export.west());}
    private TileEntityChest destination(){return (TileEntityChest)world.getTileEntity(sink.east());}
    private static void check(boolean value,String message){if(!value)throw new AssertionError(message);}

    private static FluidStack water(int amount){return new FluidStack(FluidRegistry.WATER,amount);}
    private void setupFluids(){fluidBlock(-1,LegacyPL4.TANK);fluidBlock(0,LegacyPL4.FLUID_EXPORT);fluidBlock(2,LegacyPL4.FLUID_IMPORT);fluidBlock(3,LegacyPL4.TANK);for(int x:new int[]{-1,0,1,2,3})fluidNode(x).owner=fluidOwner();fluidNode(0).side=4;fluidNode(2).side=5;}

    private String fluidOwner(){return OWNER.toString();}
    private EntityPlayer fluidPlayer(){return FakePlayerFactory.get(world,new GameProfile(OWNER,"Owner"));}
    private LegacyTile fluidNode(int x){return (LegacyTile)world.getTileEntity(new BlockPos(x,200,0));}
    private void fluidBlock(int x,LegacyBlock block){world.setBlockState(new BlockPos(x,200,0),block.getDefaultState(),3);}
    private void fluidAir(int x,int y){world.setBlockToAir(new BlockPos(x,y,0));}
    private void fluidPower(int x){world.setBlockState(new BlockPos(x,201,0),Blocks.REDSTONE_BLOCK.getDefaultState(),3);}
    private NBTTagCompound saveFluid(LegacyTile tile){return tile.writeToNBT(new NBTTagCompound());}
    private ItemStack waterBucket(){return new ItemStack(Items.WATER_BUCKET);}
    private ItemStack emptyBucket(){return new ItemStack(Items.BUCKET);}
    private int fluidCells(){int n=0;for(EntityItem item:world.getEntitiesWithinAABB(EntityItem.class,new AxisAlignedBB(-3,198,-3,6,204,3)))if(!item.isDead&&item.getItem().getItem()==LegacyPL4.FLUID_CELL&&item.getItem().getTagCompound().getCompoundTag("Contents").getInteger("Amount")==1234)n++;return n;}
    private ExternalTank externalTank(){ExternalTank tile=new ExternalTank();world.setTileEntity(new BlockPos(3,200,0),tile);return tile;}
    public static final class ExternalTank extends TileEntity implements net.minecraftforge.fluids.capability.IFluidHandler {
        final FluidTank tank=new FluidTank(16000);boolean deny,refuse,fail;int executed;
        @Override public boolean hasCapability(net.minecraftforge.common.capabilities.Capability<?> c,net.minecraft.util.EnumFacing side){return c==net.minecraftforge.fluids.capability.CapabilityFluidHandler.FLUID_HANDLER_CAPABILITY&&!deny&&side==net.minecraft.util.EnumFacing.WEST;}
        @Override public <T> T getCapability(net.minecraftforge.common.capabilities.Capability<T> c,net.minecraft.util.EnumFacing side){return hasCapability(c,side)?net.minecraftforge.fluids.capability.CapabilityFluidHandler.FLUID_HANDLER_CAPABILITY.cast(this):null;}
        public net.minecraftforge.fluids.capability.IFluidTankProperties[] getTankProperties(){return tank.getTankProperties();}
        public int fill(FluidStack f,boolean actual){if(actual){executed++;if(fail)throw new IllegalStateException("native provider failure");if(refuse)return 0;}return tank.fill(f,actual);}
        public FluidStack drain(FluidStack f,boolean actual){return tank.drain(f,actual);}
        public FluidStack drain(int n,boolean actual){return tank.drain(n,actual);}
    }
    private void setupEnergy(){fluidBlock(-1,LegacyPL4.ENERGY_BUFFER);fluidBlock(0,LegacyPL4.ENERGY_EXPORT);fluidBlock(2,LegacyPL4.ENERGY_IMPORT);fluidBlock(3,LegacyPL4.ENERGY_BUFFER);for(int x:new int[]{-1,0,1,2,3})fluidNode(x).owner=fluidOwner();fluidNode(0).side=4;fluidNode(2).side=5;}
    private int energyCells(int amount){int n=0;for(EntityItem item:world.getEntitiesWithinAABB(EntityItem.class,new AxisAlignedBB(-3,198,-3,6,204,3)))if(!item.isDead&&item.getItem().getItem()==LegacyPL4.ENERGY_CELL&&item.getItem().hasTagCompound()&&item.getItem().getTagCompound().getCompoundTag("PL4Energy").getInteger("Stored")==amount)n++;return n;}
    private ExternalEnergy externalEnergy(){ExternalEnergy tile=new ExternalEnergy();world.setTileEntity(new BlockPos(3,200,0),tile);return tile;}
    public static final class ExternalEnergy extends TileEntity implements net.minecraftforge.energy.IEnergyStorage {
        int energy,executed;boolean deny,refuse,fail,bad;
        @Override public boolean hasCapability(net.minecraftforge.common.capabilities.Capability<?> cap,net.minecraft.util.EnumFacing side){return cap==net.minecraftforge.energy.CapabilityEnergy.ENERGY&&!deny&&side==net.minecraft.util.EnumFacing.WEST;}
        @Override public <T> T getCapability(net.minecraftforge.common.capabilities.Capability<T> cap,net.minecraft.util.EnumFacing side){return hasCapability(cap,side)?net.minecraftforge.energy.CapabilityEnergy.ENERGY.cast(this):null;}
        public int receiveEnergy(int n,boolean simulate){if(simulate&&bad)return n+1;int take=Math.min(n,100000-energy);if(!simulate){executed++;if(refuse)return 0;energy+=take;if(fail)throw new IllegalStateException("energy failure after mutation");}return take;}
        public int extractEnergy(int n,boolean simulate){int take=Math.min(n,energy);if(!simulate)energy-=take;return take;}
        public int getEnergyStored(){return energy;}public int getMaxEnergyStored(){return 100000;}
        public boolean canExtract(){return !deny;}public boolean canReceive(){return !deny;}
    }

}
